http://localhost:3333/api/venues
Content-Type: application/json
X-Token: X0I4R2E3Y45YP000NENS05441BP3ST33EMHIOWPFRN20O5OD

{
  "name"     : "",
  "latitude" : 31.2094909,
  "longitude": 121.4828454,
  "accuracy" : 15,
  "altitude" : 80
}

###
http://localhost:3333/api/venues
Content-Type: application/json
X-Token: X0I4R2E3Y45YP000NENS05441BP3ST33EMHIOWPFRN20O5OD

{
  "name"     : "全家",
  "latitude" : 31.2094909,
  "longitude": 121.4828454,
  "accuracy" : 15,
  "altitude" : 80
}
