POST https://foursquare.com/oauth2/access_token?client_id=F30XUEMLQOZN2CF1ZD3KVXNVA245LOVZFLIMP05GZWAYSWY5&client_secret=KVYWFI2DDAS3PFNJDZUNWRVBXR4KDYRTYFGRTVHCBAIUNBZT&code=5G14RUDWSFH05JAOUAFMS5O4WLTFDFXI1AGOL3UXM3W4GM3K%23_%3D_&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fcheckin%2Flogin
